<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../RyzeHub.Application/RyzeHub.Application.csproj" />
    <ProjectReference Include="../RyzeHub.Contracts/RyzeHub.Contracts.csproj" />
    <ProjectReference Include="../RyzeHub.Domain/RyzeHub.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
</Project>
